// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase app.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHFcKas58Y_OmD8pMnb9m1lL9PPgmAO3g',
    appId: '1:80113388831:android:28626a80bdfbeb5799b42a',
    messagingSenderId: '80113388831',
    projectId: 'parkpilot-242eb',
    storageBucket: 'parkpilot-242eb.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHFcKas58Y_OmD8pMnb9m1lL9PPgmAO3g',
    appId: '1:80113388831:web:28626a80bdfbeb5799b42a',
    messagingSenderId: '80113388831',
    projectId: 'parkpilot-242eb',
    authDomain: 'parkpilot-242eb.firebaseapp.com',
    storageBucket: 'parkpilot-242eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHFcKas58Y_OmD8pMnb9m1lL9PPgmAO3g',
    appId: '1:80113388831:ios:28626a80bdfbeb5799b42a',
    messagingSenderId: '80113388831',
    projectId: 'parkpilot-242eb',
    storageBucket: 'parkpilot-242eb.firebasestorage.app',
    iosBundleId: 'com.parkpilot.app',
  );
}
